# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnhZ_y_WEGLxkfqVazDkj-YIvVBlYK2t

CIT-227-024/2024 KYALE JAPETH

CCS 2226 - Foundations of AI (2026)

Task 4: Search and Optimization
"""

# Graph Representation
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E', 'G'],
    'G': ['F']  # Goal state
}

#BFS Implementation
def bfs_path(graph, start, goal):
    """
    Breadth-First Search (BFS) to find a path from start to goal.
    """
    queue = [[start]]  # Queue of paths
    visited = set()

    while queue:
        path = queue.pop(0)
        node = path[-1]

        if node == goal:
            return path

        if node not in visited:
            visited.add(node)
            for neighbor in graph.get(node, []):
                new_path = path + [neighbor]
                queue.append(new_path)

    return None

#DFS Implementation
def dfs_path(graph, start, goal):
    """
    Depth-First Search (DFS) to find a path from start to goal.
    """
    stack = [[start]]  # Stack of paths
    visited = set()

    while stack:
        path = stack.pop()
        node = path[-1]

        if node == goal:
            return path

        if node not in visited:
            visited.add(node)
            for neighbor in graph.get(node, []):
                new_path = path + [neighbor]
                stack.append(new_path)

    return None

#Run both searches
start_node = 'A'
goal_node = 'G'

print(f"Initial State: {start_node} | Goal State: {goal_node}\n")

bfs_result = bfs_path(graph, start_node, goal_node)
print(f"(i) Breadth First Search Path: {' -> '.join(bfs_result)}")

dfs_result = dfs_path(graph, start_node, goal_node)
print(f"(ii) Depth First Search Path: {' -> '.join(dfs_result)}")